apiVersion: v1
kind: Service
metadata:
    name: "playground2-8871"
    labels:
        app: "playground2-8871"
spec:
    type: LoadBalancer
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "playground2-8871"