apiVersion: v1
kind: Service
metadata:
    name: "aadpi-9fce"
    labels:
        app: "aadpi-9fce"
spec:
    type: LoadBalancer
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "aadpi-9fce"