{
 "title": "Autoscale Demo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Task RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(task_list_request_total[1m]))"
    }
   ]
  },
  {
   "title": "Task List RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(task_list_request_total[1m]))"
    }
   ]
  },
  {
   "title": "Cosmos Query Response Time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (le)(cosmos_task_query_duration_bucket)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Cosmos Throttle Operations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(cosmos_throttle_count[1m]))"
    }
   ]
  },
  {
   "title": "Total transactions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(cosmos_task_query_duration_count[1m]))"
    }
   ]
  }
 ]
}