apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nodeapp-ingress
  namespace: nodeapp
  annotations:
    kubernetes.io/ingress.class: nginx
    #nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - nodeapp.aksscaledemo.seanmck.dev
    secretName: tls-secret
  rules:
  - host: nodeapp.aksscaledemo.seanmck.dev
    http:
      paths:
      - backend:
          serviceName: nodeapp
          servicePort: 80
        path: /