prometheus:
  url: http://prometheus-prometheus-oper-prometheus.prom.svc.cluster.local
  port: 9090
rules:
  custom:
  - seriesQuery: 'task_list_request_total{namespace!="", pod!=""}'
    resources:
      overrides:
        namespace: {resource: "namespace"}
        pod: {resource: "pod"}
    name:
      as: "tasks_rps"
    metricsQuery: 'round(avg(irate(<<.Series>>{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>))'